require 'config/keymaps'
require 'config/opt'
require 'plugins/autopairs'
require 'plugins/blink'
require 'plugins/gitsigns'
require 'plugins/lazydev'
require 'plugins/nvim-lspconfig'
require 'plugins/oil'
require 'plugins/surround'
require 'plugins/telescope'
require 'plugins/toggleterm'
require 'plugins/treesitter-context'
require 'plugins/treesitter'
require 'plugins/modus-themes'
vim.cmd("colorscheme darkblue")

